name: Run Google Fit Script

on:
  workflow_dispatch:  # allows manual run
  schedule:
    # Run daily at 10:30 PM IST
    - cron: "0 17 * * *"

jobs:
  google-fit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-oauthlib pandas pretty_html_table

      - name: Run Google Fit script
        env:
          GCLIENT_JSON: ${{ secrets.GCLIENT_JSON }}
          GREFRESH_TOKEN: ${{ secrets.GREFRESH_TOKEN }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_RECEIVER: ${{ secrets.GMAIL_RECEIVER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
        run: |
          python googlefit.py
